@tool
extends SceneTree

signal updated(plugin)

const VERSION = "0.2.6"
const DEFAULT_PLUGIN_URL = "https://git::@github.com/%s.git"
var DEFAULT_PLUG_DIR: String
var DEFAULT_CONFIG_PATH: String
const DEFAULT_USER_PLUG_SCRIPT_PATH = "res://plug.gd"
const DEFAULT_BASE_PLUG_SCRIPT_PATH = "res://addons/gd-plug-plus/plug.gd"

const ENV_PRODUCTION = "production"
const ENV_TEST = "test"
const ENV_FORCE = "force"
const ENV_KEEP_IMPORT_FILE = "keep_import_file"
const ENV_KEEP_IMPORT_RESOURCE_FILE = "keep_import_resource_file"

const MSG_PLUG_START_ASSERTION = "_plug_start() must be called first"

const _DOMAIN_NAME = "gd-plug-plus"
const _TRANSLATIONS_DIR = "res://addons/gd-plug-plus/translations"

var project_dir
var installation_config = ConfigFile.new()

var _installed_plugins
var _plugged_plugins = {}

var _threads = []
var _mutex = Mutex.new()
var _start_time = 0
var threadpool = _ThreadPool.new()


static func _tr(key: String) -> String:
	return TranslationServer.get_or_add_domain(_DOMAIN_NAME).translate(key)


func _load_translations():
	var domain := TranslationServer.get_or_add_domain(_DOMAIN_NAME)
	var dir := DirAccess.open(_TRANSLATIONS_DIR)
	if dir == null:
		return

	dir.list_dir_begin()
	var file_name := dir.get_next()
	while not file_name.is_empty():
		if file_name.ends_with(".translation"):
			var t = load(_TRANSLATIONS_DIR + "/" + file_name)
			if t:
				domain.add_translation(t)
		file_name = dir.get_next()
	dir.list_dir_end()


func _init():
	DEFAULT_PLUG_DIR = GitManager.get_plugged_dir()
	DEFAULT_CONFIG_PATH = DEFAULT_PLUG_DIR.path_join("index.cfg")
	_load_translations()
	threadpool.connect("all_thread_finished", request_quit)
	project_dir = DirAccess.open("res://")

func _initialize():
	var args = OS.get_cmdline_args()
	for arg in Array(args):
		args.remove_at(0)
		if "plug.gd" in arg:
			break

	var help = false
	var help_config = false
	for arg in args:
		var key = arg.to_lower()
		match key:
			"help":
				help = true
			"help-config":
				help_config = true
			"production":
				OS.set_environment(ENV_PRODUCTION, "true")
			"test":
				OS.set_environment(ENV_TEST, "true")
			"force":
				OS.set_environment(ENV_FORCE, "true")
			"keep-import-file":
				OS.set_environment(ENV_KEEP_IMPORT_FILE, "true")
			"keep-import-resource-file":
				OS.set_environment(ENV_KEEP_IMPORT_RESOURCE_FILE, "true")

	PlugLogger.debug("cmdline_args: %s" % str(args))
	_start_time = Time.get_ticks_msec()
	_plug_start()
	if help_config:
		show_config_syntax()
	elif help or args.size() == 0:
		show_syntax()
	else:
		_plugging()
		match args[0]:
			"init":
				_plug_init()
			"install", "update":
				_plug_install()
			"uninstall":
				_plug_uninstall()
			"clean":
				_plug_clean()
			"upgrade":
				_plug_upgrade()
			"status":
				_plug_status()
			"version":
				PlugLogger.info(VERSION)
			_:
				PlugLogger.info("Unknown command: %s" % args[0])
				show_syntax()
	request_quit(0)

func show_syntax():
	PlugLogger.debug("gd-plug - Minimal plugin manager for Godot")
	PlugLogger.debug("")
	PlugLogger.debug("Usage: godot --headless -s plug.gd action [options...]")
	PlugLogger.debug("")
	PlugLogger.debug("Actions:")
	var actions = {
		"init": "Initialize current project by creating plug.gd at root",
		"status": "Check the status of plugins(installed, added or removed), execute this command whenever in doubts",
		"install(alias update)": "Install or update plugins based on plug.gd",
		"uninstall": "Uninstall all plugins, regardless of plug.gd",
		"clean": "Clean unused files/folders from /.plugged",
		"upgrade": "Upgrade addons/gd-plug-plus/plug.gd to the latest version",
		"version": "Print current version of gd-plug",
	}
	for action_name in actions:
		PlugLogger.debug("    %-24s %s" % [action_name, actions[action_name]])

	PlugLogger.debug("")
	PlugLogger.debug("Options:")
	var options = {
		"production": "Install only plugins not marked as dev, or uninstall already installed dev plugins",
		"test": "Testing mode, no files will actually be installed/uninstalled",
		"force": "Force gd-plug to overwrite destination files when running install command. *WARNING: Check README for more details*",
		"keep-import-file": "Keep \".import\" files generated by plugin, when run uninstall command",
		"keep-import-resource-file": "Keep files located in \".import\" that generated by plugin, when run uninstall command",
		"help": "Show this help",
		"help-config": "plug.gd configuration documentation"
	}
	for option_name in options:
		PlugLogger.debug("    %-28s %s" % [option_name, options[option_name]])
	PlugLogger.debug("")

func show_config_syntax():
	PlugLogger.debug("Configs: plug(src, args={})")
	PlugLogger.debug("")
	PlugLogger.debug("Sources:")
	PlugLogger.debug("    Github repo: \"username/repo\", for example, \"imjp94/gd-plug\"")
	PlugLogger.debug("    or")
	PlugLogger.debug("    Any valid git url, for example, \"git@github.com:username/repo.git\"")
	PlugLogger.debug("")
	PlugLogger.debug("Arguments:")
	var arguments = {
		"include": "Array of strings that define what files or directory to include. Only \"addons/\" will be included if omitted",
		"exclude": "Array of strings that define what files or directory to exclude",
		"branch": "Name of branch to freeze to",
		"tag": "Name of tag to freeze to",
		"commit": "Commit hash string to freeze to, must be full length 40 digits commit-hash, for example, 7a642f90d3fb88976dd913051de994e58e838d1a",
		"dev": "Boolean to mark the plugin as dev or not, plugin marked as dev will not be installed when production command given",
		"on_updated": "Post update hook, a function name declared in plug.gd that will be called whenever the plugin installed/updated"
	}
	for argument_name in arguments:
		PlugLogger.debug("    %-16s %s" % [argument_name, arguments[argument_name]])
	PlugLogger.debug("")

func _process(delta):
	threadpool.process(delta)

func _finalize():
	_plug_end()
	threadpool.stop()
	PlugLogger.info(_tr("LOG_CLI_FINISHED") % ((Time.get_ticks_msec() - _start_time) / 1000.0))

func _on_updated(plugin):
	pass

func _plugging():
	pass

func request_quit(exit_code=-1):
	if threadpool.is_all_thread_finished() and threadpool.is_all_task_finished():
		quit(exit_code)
		return true
	PlugLogger.debug("Request quit declined, threadpool is still running")
	return false

func _plug_start():
	PlugLogger.debug("Plug start")
	if not DirAccess.dir_exists_absolute(DEFAULT_PLUG_DIR):
		if DirAccess.make_dir_recursive_absolute(DEFAULT_PLUG_DIR) == OK:
			PlugLogger.debug("Make dir %s for plugin installation" % DEFAULT_PLUG_DIR)
	if installation_config.load(DEFAULT_CONFIG_PATH) == OK:
		PlugLogger.debug("Installation config loaded")
	else:
		PlugLogger.debug("Installation config not found")
	_installed_plugins = installation_config.get_value("plugin", "installed", {})

func _plug_end():
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	var test = !OS.get_environment(ENV_TEST).is_empty()
	if not test:
		installation_config.set_value("plugin", "installed", _installed_plugins)
		if installation_config.save(DEFAULT_CONFIG_PATH) == OK:
			PlugLogger.debug("Plugged config saved")
		else:
			PlugLogger.info("Failed to save plugged config")
	else:
		PlugLogger.debug("Skipped saving of plugged config in test mode")
	_installed_plugins = null

func _plug_init():
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	PlugLogger.info(_tr("LOG_CLI_INIT"))
	if FileAccess.file_exists(DEFAULT_USER_PLUG_SCRIPT_PATH):
		PlugLogger.info(_tr("LOG_CLI_FILE_EXISTS") % DEFAULT_USER_PLUG_SCRIPT_PATH)
	else:
		var file = FileAccess.open(DEFAULT_USER_PLUG_SCRIPT_PATH, FileAccess.WRITE)
		file.store_string(INIT_PLUG_SCRIPT)
		file.close()
		PlugLogger.info(_tr("LOG_CLI_CREATED_FILE") % DEFAULT_USER_PLUG_SCRIPT_PATH)

func _plug_install():
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	threadpool.active = false
	PlugLogger.info(_tr("LOG_CLI_INSTALLING"))
	for plugin in _plugged_plugins.values():
		var installed = plugin.name in _installed_plugins
		if installed:
			var installed_plugin = get_installed_plugin(plugin.name)
			if (installed_plugin.dev or plugin.dev) and OS.get_environment(ENV_PRODUCTION):
				PlugLogger.debug("Remove dev plugin for production: %s" % plugin.name)
				threadpool.enqueue_task(uninstall_plugin.bind(installed_plugin))
			else:
				threadpool.enqueue_task(update_plugin.bind(plugin))
		else:
			threadpool.enqueue_task(install_plugin.bind(plugin))

	var removed_plugins = []
	for plugin in _installed_plugins.values():
		var removed = not (plugin.name in _plugged_plugins)
		if removed:
			removed_plugins.append(plugin)
	if removed_plugins:
		threadpool.disconnect("all_thread_finished", request_quit)
		if not threadpool.is_all_thread_finished():
			threadpool.active = true
			await threadpool.all_thread_finished
			threadpool.active = false
			PlugLogger.debug("All installation finished! Ready to uninstall removed plugins...")
		threadpool.connect("all_thread_finished", request_quit)
		for plugin in removed_plugins:
			threadpool.enqueue_task(uninstall_plugin.bind(plugin), Thread.PRIORITY_LOW)
	threadpool.active = true

func _plug_uninstall():
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	threadpool.active = false
	PlugLogger.info(_tr("LOG_CLI_UNINSTALLING"))
	for plugin in _installed_plugins.values():
		var installed_plugin = get_installed_plugin(plugin.name)
		threadpool.enqueue_task(uninstall_plugin.bind(installed_plugin), Thread.PRIORITY_LOW)
	threadpool.active = true

func _plug_clean():
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	threadpool.active = false
	PlugLogger.info(_tr("LOG_CLI_CLEANING"))
	for repo_path in _list_repo_dirs(DEFAULT_PLUG_DIR):
		if not (repo_path in _installed_plugins):
			PlugLogger.debug("Remove %s" % repo_path)
			threadpool.enqueue_task(directory_delete_recursively.bind(DEFAULT_PLUG_DIR.path_join(repo_path)))
	threadpool.active = true

func _plug_upgrade():
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	threadpool.active = false
	PlugLogger.info(_tr("LOG_CLI_UPGRADING"))
	plug("imjp94/gd-plug")
	var gd_plug = _plugged_plugins["gd-plug"]
	OS.set_environment(ENV_FORCE, "true")
	threadpool.enqueue_task(install_plugin.bind(gd_plug))
	threadpool.disconnect("all_thread_finished", request_quit)
	if not threadpool.is_all_thread_finished():
		threadpool.active = true
		await threadpool.all_thread_finished
		threadpool.active = false
		PlugLogger.debug("All installation finished! Ready to uninstall removed plugins...")
	threadpool.connect("all_thread_finished", request_quit)
	threadpool.enqueue_task(directory_delete_recursively.bind(gd_plug.plug_dir))
	threadpool.active = true

func _plug_status():
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	threadpool.active = false
	PlugLogger.info(_tr("LOG_CLI_INSTALLED_SUMMARY") % _installed_plugins.size())
	var new_plugins = _plugged_plugins.duplicate()
	var has_checking_plugin = false
	var removed_plugins = []
	for plugin in _installed_plugins.values():
		PlugLogger.info("- {name} - {url}".format(plugin))
		new_plugins.erase(plugin.name)
		var removed = not (plugin.name in _plugged_plugins)
		if removed:
			removed_plugins.append(plugin)
		else:
			threadpool.enqueue_task(check_plugin.bind(_plugged_plugins[plugin.name]))
			has_checking_plugin = true
	if has_checking_plugin:
		threadpool.disconnect("all_thread_finished", request_quit)
		threadpool.active = true
		await threadpool.all_thread_finished
		threadpool.active = false
		threadpool.connect("all_thread_finished", request_quit)
		PlugLogger.debug("Finished checking plugins, ready to proceed")
	if new_plugins:
		PlugLogger.info(_tr("LOG_CLI_PLUGGED_SUMMARY") % new_plugins.size())
		for plugin in new_plugins.values():
			var is_new = not (plugin.name in _installed_plugins)
			if is_new:
				PlugLogger.info("- {name} - {url}".format(plugin))
	if removed_plugins:
		PlugLogger.info(_tr("LOG_CLI_UNPLUGGED_SUMMARY") % removed_plugins.size())
		for plugin in removed_plugins:
			PlugLogger.info("- %s" % plugin.name)
	var orphan_dirs = []
	for repo_path in _list_repo_dirs(DEFAULT_PLUG_DIR):
		if not (repo_path in _installed_plugins):
			orphan_dirs.append(repo_path)
	if orphan_dirs:
		PlugLogger.info(_tr("LOG_CLI_ORPHAN_FOUND") % orphan_dirs.size())
		for dir in orphan_dirs:
			PlugLogger.info("- %s" % dir)
	threadpool.active = true

	if has_checking_plugin:
		request_quit()

func plug(repo, args={}):
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	repo = repo.strip_edges()
	var plugin_name = get_plugin_name_from_repo(repo)
	if plugin_name in _plugged_plugins:
		PlugLogger.info(_tr("LOG_CLI_ALREADY_PLUGGED") % plugin_name)
		return
	var plugin = {}
	plugin.name = plugin_name
	plugin.url = ""
	if ":" in repo:
		plugin.url = repo
	elif repo.find("/") == repo.rfind("/"):
		plugin.url = DEFAULT_PLUGIN_URL % repo
	else:
		PlugLogger.info(_tr("LOG_CLI_INVALID_REPO") % repo)
	plugin.plug_dir = DEFAULT_PLUG_DIR.path_join(plugin.name)

	var is_valid = true
	plugin.include = args.get("include", [])
	is_valid = is_valid and validate_var_type(plugin, "include", TYPE_ARRAY, "Array")
	plugin.exclude = args.get("exclude", [])
	is_valid = is_valid and validate_var_type(plugin, "exclude", TYPE_ARRAY, "Array")
	plugin.branch = args.get("branch", "")
	is_valid = is_valid and validate_var_type(plugin, "branch", TYPE_STRING, "String")
	plugin.tag = args.get("tag", "")
	is_valid = is_valid and validate_var_type(plugin, "tag", TYPE_STRING, "String")
	plugin.commit = args.get("commit", "")
	is_valid = is_valid and validate_var_type(plugin, "commit", TYPE_STRING, "String")
	if not plugin.commit.is_empty():
		var is_valid_commit = plugin.commit.length() == 40
		if not is_valid_commit:
			PlugLogger.debug("Expected full length 40 digits commit-hash string, given %s" % plugin.commit)
		is_valid = is_valid and is_valid_commit
	plugin.dev = args.get("dev", false)
	is_valid = is_valid and validate_var_type(plugin, "dev", TYPE_BOOL, "Boolean")
	plugin.on_updated = args.get("on_updated", "")
	is_valid = is_valid and validate_var_type(plugin, "on_updated", TYPE_STRING, "String")
	plugin.install_root = args.get("install_root", "")
	is_valid = is_valid and validate_var_type(plugin, "install_root", TYPE_STRING, "String")

	if is_valid:
		_plugged_plugins[plugin.name] = plugin
		PlugLogger.debug("Plug: %s" % str(plugin))
	else:
		PlugLogger.info("Failed to plug %s, validation error" % plugin.name)

func install_plugin(plugin):
	var test = !OS.get_environment(ENV_TEST).is_empty()
	var can_install = OS.get_environment(ENV_PRODUCTION).is_empty() if plugin.dev else true
	if can_install:
		PlugLogger.info(_tr("LOG_CLI_INSTALLING_PLUGIN") % plugin.name)
		var result = is_plugin_downloaded(plugin)
		if result != OK:
			result = download(plugin)
		else:
			PlugLogger.info(_tr("LOG_CLI_PLUGIN_DOWNLOADED"))

		if result == OK:
			install(plugin)
		else:
			PlugLogger.info(_tr("LOG_CLI_INSTALL_FAILED") % [plugin.name, result])

func uninstall_plugin(plugin):
	var test = !OS.get_environment(ENV_TEST).is_empty()
	PlugLogger.info(_tr("LOG_CLI_UNINSTALLING_PLUGIN") % plugin.name)
	uninstall(plugin)
	directory_delete_recursively(plugin.plug_dir, {"exclude": [DEFAULT_CONFIG_PATH], "test": test})

func update_plugin(plugin, checking=false):
	if not (plugin.name in _installed_plugins):
		PlugLogger.info("%s new plugin" % plugin.name)
		return true

	var git = _GitExecutable.new(plugin.plug_dir)
	var installed_plugin = get_installed_plugin(plugin.name)
	var changes = compare_plugins(plugin, installed_plugin)
	var should_clone = false
	var should_pull = false
	var should_reinstall = false

	if plugin.tag or plugin.commit:
		for rev in ["tag", "commit"]:
			var freeze_at = plugin[rev]
			if freeze_at:
				PlugLogger.info(_tr("LOG_CLI_COMMIT_FROZEN") % [plugin.name, rev, freeze_at])
				break
	else:
		var ahead_behind = []
		if git.fetch("origin " + plugin.branch if plugin.branch else "origin").exit == OK:
			ahead_behind = git.get_commit_comparison("HEAD", "origin/" + plugin.branch if plugin.branch else "origin")
		var is_commit_behind = !!ahead_behind[1] if ahead_behind.size() == 2 else false
		if is_commit_behind:
			PlugLogger.info(_tr("LOG_CLI_BEHIND") % [plugin.name, ahead_behind[1]])
			should_pull = true
		else:
			PlugLogger.info(_tr("LOG_CLI_UP_TO_DATE") % plugin.name)

	if changes:
		PlugLogger.info(_tr("LOG_CLI_CHANGES") % [plugin.name, changes])
		should_reinstall = true
		if "url" in changes or "branch" in changes or "tag" in changes or "commit" in changes:
			PlugLogger.info(_tr("LOG_CLI_SETTING_CHANGED") % plugin.name)
			should_clone = true

	if not checking:
		if should_clone:
			PlugLogger.info(_tr("LOG_CLI_CLONING_FROM") % [plugin.name, plugin.url])
			var test = !OS.get_environment(ENV_TEST).is_empty()
			uninstall(get_installed_plugin(plugin.name))
			directory_delete_recursively(plugin.plug_dir, {"exclude": [DEFAULT_CONFIG_PATH], "test": test})
			if download(plugin) == OK:
				install(plugin)
		elif should_pull:
			PlugLogger.info(_tr("LOG_CLI_PULLING") % [plugin.name, plugin.url])
			uninstall(get_installed_plugin(plugin.name))
			if git.pull().exit == OK:
				install(plugin)
		elif should_reinstall:
			PlugLogger.info(_tr("LOG_CLI_REINSTALLING") % plugin.name)
			uninstall(get_installed_plugin(plugin.name))
			install(plugin)

func check_plugin(plugin):
	update_plugin(plugin, true)

func download(plugin):
	PlugLogger.debug("Downloading %s from %s..." % [plugin.name, plugin.url])
	var test = !OS.get_environment(ENV_TEST).is_empty()
	if DirAccess.dir_exists_absolute(plugin.plug_dir):
		directory_delete_recursively(plugin.plug_dir)
	DirAccess.make_dir_recursive_absolute(plugin.plug_dir)
	var result = _GitExecutable.new(plugin.plug_dir).clone(plugin.url, plugin.plug_dir, {"branch": plugin.branch, "tag": plugin.tag, "commit": plugin.commit})
	if result.exit == OK:
		PlugLogger.info(_tr("LOG_CLI_DOWNLOAD_OK") % plugin.name)
	else:
		PlugLogger.info(_tr("LOG_CLI_DOWNLOAD_FAIL") % plugin.name)
		directory_delete_recursively(plugin.plug_dir, {"exclude": [DEFAULT_CONFIG_PATH], "test": test})
	DirAccess.remove_absolute(plugin.plug_dir)
	return result.exit

func install(plugin):
	var include = plugin.get("include", [])
	if include.is_empty():
		include = ["addons/"]
	if OS.get_environment(ENV_FORCE).is_empty() and OS.get_environment(ENV_TEST).is_empty():
		var is_exists = false
		var dest_files = directory_copy_recursively(plugin.plug_dir, "res://" + plugin.install_root, {"include": include, "exclude": plugin.exclude, "test": true, "silent_test": true})
		for dest_file in dest_files:
			if project_dir.file_exists(dest_file):
				PlugLogger.info(_tr("LOG_CLI_OVERWRITE_WARN") % [plugin.name, dest_file])
				is_exists = true
		if is_exists:
			PlugLogger.info(_tr("LOG_CLI_OVERWRITE_ABORT") % plugin.name)
			return ERR_ALREADY_EXISTS

	PlugLogger.info(_tr("LOG_CLI_INSTALLING_FILES") % plugin.name)
	var test = !OS.get_environment(ENV_TEST).is_empty()
	var dest_files = directory_copy_recursively(plugin.plug_dir, "res://" + plugin.install_root, {"include": include, "exclude": plugin.exclude, "test": test})
	plugin.dest_files = dest_files
	PlugLogger.info(_tr("LOG_CLI_INSTALLED_FILES") % [dest_files.size(), plugin.name])
	if plugin.name != "gd-plug":
		set_installed_plugin(plugin)
	
	PlugLogger.debug("Execute \"_on_updated\" function for %s" % plugin.name)
	_on_updated(plugin.duplicate())
	if plugin.on_updated:
		if has_method(plugin.on_updated):
			PlugLogger.debug("Execute post-update function \"%s\" for %s" % [plugin.on_updated, plugin.name])
			call(plugin.on_updated, plugin.duplicate())
	PlugLogger.debug("Emit \"updated\" signal for %s" % plugin.name)
	emit_signal("updated", plugin.duplicate())
	return OK

func uninstall(plugin):
	var test = !OS.get_environment(ENV_TEST).is_empty()
	var keep_import_file = !OS.get_environment(ENV_KEEP_IMPORT_FILE).is_empty()
	var keep_import_resource_file = !OS.get_environment(ENV_KEEP_IMPORT_RESOURCE_FILE).is_empty()
	var dest_files = plugin.get("dest_files", [])
	PlugLogger.debug("Uninstalling %d files for %s..." % [dest_files.size(), plugin.name])
	directory_remove_batch(dest_files, {"test": test, "keep_import_file": keep_import_file, "keep_import_resource_file": keep_import_resource_file})
	PlugLogger.info(_tr("LOG_CLI_UNINSTALLED_FILES") % [dest_files.size(), plugin.name])
	remove_installed_plugin(plugin.name)

func is_plugin_downloaded(plugin):
	if not DirAccess.dir_exists_absolute(plugin.plug_dir.path_join(".git")):
		return

	var git = _GitExecutable.new(plugin.plug_dir)
	return git.is_up_to_date(plugin)

func get_installed_plugin(plugin_name):
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	_mutex.lock()
	var installed_plugin = _installed_plugins[plugin_name]
	_mutex.unlock()
	return installed_plugin

func set_installed_plugin(plugin):
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	_mutex.lock()
	_installed_plugins[plugin.name] = plugin
	_mutex.unlock()

func remove_installed_plugin(plugin_name):
	assert(_installed_plugins != null, MSG_PLUG_START_ASSERTION)
	_mutex.lock()
	var result = _installed_plugins.erase(plugin_name)
	_mutex.unlock()
	return result

func directory_copy_recursively(from, to, args={}):
	var include = args.get("include", [])
	var exclude = args.get("exclude", [])
	var test = args.get("test", false)
	var silent_test = args.get("silent_test", false)
	var dir = DirAccess.open(from)
	dir.include_hidden = true
	var dest_files = []
	if dir.get_open_error() == OK:
		dir.list_dir_begin() # TODOGODOT4 fill missing arguments https://github.com/godotengine/godot/pull/40547
		var file_name = dir.get_next()
		while not file_name.is_empty():
			var source = dir.get_current_dir() + ("/" if dir.get_current_dir() != "res://" else "") + file_name
			var dest = to + ("/" if to != "res://" else "") + file_name
			
			if dir.current_is_dir():
				dest_files += directory_copy_recursively(source, dest, args)
			else:
				for include_key in include:
					if include_key in source:
						var is_excluded = false
						for exclude_key in exclude:
							if exclude_key in source:
								is_excluded = true
								break
						if not is_excluded:
							if test:
								if not silent_test: PlugLogger.debug("[TEST] Writing to %s" % dest)
							else:
								dir.make_dir_recursive(to)
								if dir.copy(source, dest) == OK:
									PlugLogger.debug("Copy from %s to %s" % [source, dest])
							dest_files.append(dest)
						break
			file_name = dir.get_next()
		dir.list_dir_end()
	else:
		PlugLogger.info("Failed to access path: %s" % from)
	
	return dest_files

func directory_delete_recursively(dir_path, args={}):
	var remove_empty_directory = args.get("remove_empty_directory", true)
	var exclude = args.get("exclude", [])
	var test = args.get("test", false)
	var silent_test = args.get("silent_test", false)
	var dir = DirAccess.open(dir_path)
	dir.include_hidden = true
	if dir.get_open_error() == OK:
		dir.list_dir_begin() # TODOGODOT4 fill missing arguments https://github.com/godotengine/godot/pull/40547
		var file_name = dir.get_next()
		while not file_name.is_empty():
			var source = dir.get_current_dir() + ("/" if dir.get_current_dir() != "res://" else "") + file_name
			
			if dir.current_is_dir():
				var sub_dir = directory_delete_recursively(source, args)
				if remove_empty_directory:
					if test:
						if not silent_test: PlugLogger.debug("[TEST] Remove empty directory: %s" % sub_dir.get_current_dir())
					else:
						if source.get_file() == ".git":
							var empty_dir_path = ProjectSettings.globalize_path(source)
							var exit = FAILED
							match OS.get_name():
								"Windows":
									empty_dir_path = "\"%s\"" % empty_dir_path
									empty_dir_path = empty_dir_path.replace("/", "\\")
									var cmd = "rd /s /q %s" % empty_dir_path
									exit = OS.execute("cmd", ["/C", cmd])
								"X11", "OSX", "Server":
									empty_dir_path = "\'%s\'" % empty_dir_path
									var cmd = "rm -rf %s" % empty_dir_path
									exit = OS.execute("bash", ["-c", cmd])
							if exit == OK:
								PlugLogger.debug("Remove empty directory: %s" % sub_dir.get_current_dir())
							else:
								PlugLogger.debug("Failed to remove empty directory: %s" % sub_dir.get_current_dir())
						else:
							if dir.remove(sub_dir.get_current_dir()) == OK:
								PlugLogger.debug("Remove empty directory: %s" % sub_dir.get_current_dir())
			else:
				var excluded = false
				for exclude_key in exclude:
					if source in exclude_key:
						excluded = true
						break
				if not excluded:
					if test:
						if not silent_test: PlugLogger.debug("[TEST] Remove file: %s" % source)
					else:
						if dir.remove(file_name) == OK:
							PlugLogger.debug("Remove file: %s" % source)
			file_name = dir.get_next()
		dir.list_dir_end()
	else:
		PlugLogger.info("Failed to access path: %s" % dir_path)

	if remove_empty_directory:
		dir.remove(dir.get_current_dir())

	return dir

func directory_remove_batch(files, args={}):
	var remove_empty_directory = args.get("remove_empty_directory", true)
	var keep_import_file = args.get("keep_import_file", false)
	var keep_import_resource_file = args.get("keep_import_resource_file", false)
	var test = args.get("test", false)
	var silent_test = args.get("silent_test", false)
	var dirs = {}
	for file in files:
		var file_dir = file.get_base_dir()
		var file_name =file.get_file()
		var dir = dirs.get(file_dir)
		
		if not dir:
			dir = DirAccess.open(file_dir)
			dirs[file_dir] = dir

		if file.ends_with(".import"):
			if not keep_import_file:
				_remove_import_file(dir, file, keep_import_resource_file, test, silent_test)
		else:
			if test:
				if not silent_test: PlugLogger.debug("[TEST] Remove file: " + file)
			else:
				if dir.remove(file_name) == OK:
					PlugLogger.debug("Remove file: " + file)
			if not keep_import_file:
				_remove_import_file(dir, file + ".import", keep_import_resource_file, test, silent_test)
		
	for dir in dirs.values():
		var slash_count = dir.get_current_dir().count("/") - 2
		if test:
			if not silent_test: PlugLogger.debug("[TEST] Remove empty directory: %s" % dir.get_current_dir())
		else:
			if dir.remove(dir.get_current_dir()) == OK:
				PlugLogger.debug("Remove empty directory: %s" % dir.get_current_dir())
		PlugLogger.debug("Removing empty ancestor directory for %s..." % dir.get_current_dir())
		var current_dir = dir.get_current_dir()
		for i in slash_count:
			current_dir = current_dir.get_base_dir()
			var d = DirAccess.open(current_dir)
			if d.get_open_error() == OK:
				if test:
					if not silent_test: PlugLogger.debug("[TEST] Remove empty ancestor directory: %s" % d.get_current_dir())
				else:
					if d.remove(d.get_current_dir()) == OK:
						PlugLogger.debug("Remove empty ancestor directory: %s" % d.get_current_dir())

func _remove_import_file(dir, file, keep_import_resource_file=false, test=false, silent_test=false):
	if not dir.file_exists(file):
		return

	if not keep_import_resource_file:
		var import_config = ConfigFile.new()
		if import_config.load(file) == OK:
			var metadata = import_config.get_value("remap", "metadata", {})
			var imported_formats = metadata.get("imported_formats", [])
			if imported_formats:
				for format in imported_formats:
					_remove_import_resource_file(dir, import_config, "." + format, test)
			else:
				_remove_import_resource_file(dir, import_config, "", test)
	if test:
		if not silent_test: PlugLogger.debug("[TEST] Remove import file: " + file)
	else:
		if dir.remove(file) == OK:
			PlugLogger.debug("Remove import file: " + file)
		else:
			PlugLogger.debug("Failed to remove import file: " + file)

func _remove_import_resource_file(dir, import_config, import_format="", test=false):
	var import_resource_file = import_config.get_value("remap", "path" + import_format, "")
	var checksum_file = import_resource_file.trim_suffix("." + import_resource_file.get_extension()) + ".md5" if import_resource_file else ""
	if import_resource_file:
		if dir.file_exists(import_resource_file):
			if test:
				PlugLogger.debug("[IMPORT] Remove import resource file: " + import_resource_file)
			else:
				if dir.remove(import_resource_file) == OK:
					PlugLogger.debug("Remove import resource file: " + import_resource_file)
	if checksum_file:
		checksum_file = checksum_file.replace(import_format, "")
		if dir.file_exists(checksum_file):
			if test:
				PlugLogger.debug("[IMPORT] Remove import checksum file: " + checksum_file)
			else:
				if dir.remove(checksum_file) == OK:
					PlugLogger.debug("Remove import checksum file: " + checksum_file)

func compare_plugins(p1, p2):
	var changed_keys = []
	for key in p1.keys():
		var v1 = p1[key]
		var v2 = p2[key]
		if v1 != v2:
			changed_keys.append(key)
	return changed_keys

func get_plugin_name_from_repo(repo):
	repo = repo.replace(".git", "").trim_suffix("/")
	var parts = repo.split("/")
	if parts.size() >= 2:
		return parts[-2] + "/" + parts[-1]
	return repo

## Enumerate all user/repo directories under base_dir (two levels deep).
func _list_repo_dirs(base_dir: String) -> PackedStringArray:
	var result: PackedStringArray = []
	var top = DirAccess.open(base_dir)
	if top == null or top.get_open_error() != OK:
		return result
	top.include_hidden = true
	top.list_dir_begin()
	var user_dir = top.get_next()
	while not user_dir.is_empty():
		if top.current_is_dir() and not user_dir.begins_with("."):
			var user_path = base_dir.path_join(user_dir)
			var sub = DirAccess.open(user_path)
			if sub != null and sub.get_open_error() == OK:
				sub.include_hidden = true
				sub.list_dir_begin()
				var repo_dir = sub.get_next()
				while not repo_dir.is_empty():
					if sub.current_is_dir() and not repo_dir.begins_with("."):
						result.append(user_dir + "/" + repo_dir)
					repo_dir = sub.get_next()
				sub.list_dir_end()
		user_dir = top.get_next()
	top.list_dir_end()
	return result


func validate_var_type(obj, var_name, type, type_string):
	var value = obj.get(var_name)
	var is_valid = typeof(value) == type
	if not is_valid:
		PlugLogger.debug("Expected variable \"%s\" to be %s, given %s" % [var_name, type_string, value])
	return is_valid

const INIT_PLUG_SCRIPT = \
"""extends "res://addons/gd-plug-plus/plug.gd"

func _plugging():
	# Declare plugins with plug(repo, args)
	# For example, clone from github repo("user/repo_name")
	# plug("imjp94/gd-YAFSM") # By default, gd-plug will only install anything from "addons/" directory
	# Or you can explicitly specify which file/directory to include
	# plug("imjp94/gd-YAFSM", {"include": ["addons/"]}) # By default, gd-plug will only install anything from "addons/" directory
	pass
"""

class _GitExecutable extends RefCounted:
	var cwd = ""

	func _init(p_cwd):
		cwd = p_cwd

	func _execute(command, output=[], read_stderr=false):
		var cmd = "cd '%s' && %s" % [cwd, command]
		var exit = FAILED
		match OS.get_name():
			"Windows":
				cmd = cmd.replace("\'", "\"")
				cmd = cmd if read_stderr else "%s 2> nul" % cmd
				PlugLogger.debug("Execute \"%s\"" % cmd)
				exit = OS.execute("cmd", ["/C", cmd], output, read_stderr)
			"macOS", "Linux", "FreeBSD", "NetBSD", "OpenBSD", "BSD":
				cmd = cmd if read_stderr else "%s 2>/dev/null" % cmd
				PlugLogger.debug("Execute \"%s\"" % cmd)
				exit = OS.execute("bash", ["-c", cmd], output, read_stderr)
			var unhandled_os:
				PlugLogger.debug("Unexpected OS: %s" % unhandled_os)
		PlugLogger.debug("Execution ended(code:%d): %s" % [exit, output])
		return exit

	func init():
		PlugLogger.debug("Initializing git at %s..." % cwd)
		var output = []
		var exit = _execute("git init", output)
		PlugLogger.debug("Successfully init" if exit == OK else "Failed to init")
		return {"exit": exit, "output": output}

	func clone(src, dest, args={}):
		PlugLogger.debug("Cloning from %s to %s..." % [src, dest])
		var output = []
		var branch = args.get("branch", "")
		var tag = args.get("tag", "")
		var commit = args.get("commit", "")
		var command = "git clone --depth=1 --progress '%s' '%s'" % [src, dest]
		if branch or tag:
			command = "git clone --depth=1 --single-branch --branch %s '%s' '%s'" % [branch if branch else tag, src, dest]
		elif commit:
			return clone_commit(src, dest, commit)
		var exit = _execute(command, output)
		PlugLogger.debug("Successfully cloned from %s" % src if exit == OK else "Failed to clone from %s" % src)
		return {"exit": exit, "output": output}

	func clone_commit(src, dest, commit):
		var output = []
		if commit.length() < 40:
			PlugLogger.debug("Expected full length 40 digits commit-hash to clone specific commit, given {%s}" % commit)
			return {"exit": FAILED, "output": output}

		PlugLogger.debug("Cloning from %s to %s @ %s..." % [src, dest, commit])
		var result = init()
		if result.exit == OK:
			result = remote_add("origin", src)
			if result.exit == OK:
				result = fetch("%s %s" % ["origin", commit])
				if result.exit == OK:
					result = reset("--hard", "FETCH_HEAD")
		return result

	func fetch(rm="--all"):
		PlugLogger.debug("Fetching %s..." % rm.replace("--", ""))
		var output = []
		var exit = _execute("git fetch %s" % rm, output)
		PlugLogger.debug("Successfully fetched" if exit == OK else "Failed to fetch")
		return {"exit": exit, "output": output}

	func pull():
		PlugLogger.debug("Pulling...")
		var output = []
		var exit = _execute("git pull --rebase", output)
		PlugLogger.debug("Successfully pulled" if exit == OK else "Failed to pull")
		return {"exit": exit, "output": output}

	func remote_add(name, src):
		PlugLogger.debug("Adding remote %s@%s..." % [name, src])
		var output = []
		var exit = _execute("git remote add %s '%s'" % [name, src], output)
		PlugLogger.debug("Successfully added remote" if exit == OK else "Failed to add remote")
		return {"exit": exit, "output": output}

	func reset(mode, to):
		PlugLogger.debug("Resetting %s %s..." % [mode, to])
		var output = []
		var exit = _execute("git reset %s %s" % [mode, to], output)
		PlugLogger.debug("Successfully reset" if exit == OK else "Failed to reset")
		return {"exit": exit, "output": output}

	func get_commit_comparison(branch_a, branch_b):
		var output = []
		var exit = _execute("git rev-list --count --left-right %s...%s" % [branch_a, branch_b], output)
		var raw_ahead_behind = output[0].split("\t")
		var ahead_behind = []
		for msg in raw_ahead_behind:
			ahead_behind.append(msg.to_int())
		return ahead_behind if exit == OK else []

	func get_current_branch():
		var output = []
		var exit = _execute("git rev-parse --abbrev-ref HEAD", output)
		return output[0] if exit == OK else ""

	func get_current_tag():
		var output = []
		var exit = _execute("git describe --tags --exact-match", output)
		return output[0] if exit == OK else ""

	func get_current_commit():
		var output = []
		var exit = _execute("git rev-parse --short HEAD", output)
		return output[0] if exit == OK else ""

	func is_detached_head():
		var output = []
		var exit = _execute("git rev-parse --short HEAD", output)
		return (!!output[0]) if exit == OK else true

	func is_up_to_date(args={}):
		if fetch().exit == OK:
			var branch = args.get("branch", "")
			var tag = args.get("tag", "")
			var commit = args.get("commit", "")
	
			if branch:
				if branch == get_current_branch():
					return FAILED if is_detached_head() else OK
			elif tag:
				if tag == get_current_tag():
					return OK
			elif commit:
				if commit == get_current_commit():
					return OK
	
			var ahead_behind = get_commit_comparison("HEAD", "origin")
			var is_commit_behind = !!ahead_behind[1] if ahead_behind.size() == 2 else false
			return FAILED if is_commit_behind else OK
		return FAILED

class _ThreadPool extends RefCounted:
	signal all_thread_finished()

	var active = true

	var _threads = []
	var _finished_threads = []
	var _mutex = Mutex.new()
	var _tasks = []

	func _init():
		_threads.resize(OS.get_processor_count())

	func _execute_task(task):
		var thread = _get_thread()
		var can_execute = thread
		if can_execute:
			task.thread = weakref(thread)
			var callable = task.get("callable")
			thread.start(_execute.bind(task), task.priority)
			PlugLogger.debug("Execute task %s.%s() " % [callable.get_object(), callable.get_method()])
		return can_execute

	func _execute(args):
		var callable = args.get("callable")
		callable.call()
		_mutex.lock()
		var thread = args.thread.get_ref()
		_threads[_threads.find(thread)] = null
		_finished_threads.append(thread)
		var all_finished = is_all_thread_finished()
		_mutex.unlock()

		PlugLogger.debug("Execution finished %s.%s() " % [callable.get_object(), callable.get_method()])
		if all_finished:
			PlugLogger.debug("All thread finished")
			emit_signal("all_thread_finished")

	func _flush_tasks():
		if _tasks.size() == 0:
			return

		var executed = true
		while executed:
			var task = _tasks.pop_front()
			if task != null:
				executed = _execute_task(task)
				if not executed:
					_tasks.push_front(task)
			else:
				executed = false

	func _flush_threads():
		for i in _finished_threads.size():
			var thread = _finished_threads.pop_front()
			if not thread.is_alive():
				thread.wait_to_finish()

	func enqueue_task(callable, priority=1):
		enqueue({"callable": callable, "priority": priority})

	func enqueue(task):
		var can_execute = false
		if active:
			can_execute = _execute_task(task)
		if not can_execute:
			_tasks.append(task)

	func process(delta):
		if active:
			_flush_tasks()
			_flush_threads()

	func stop():
		_tasks.clear()
		_flush_threads()

	func _get_thread():
		var thread
		for i in OS.get_processor_count():
			var t = _threads[i]
			if t:
				if not t.is_started():
					thread = t
					break
			else:
				thread = Thread.new()
				_threads[i] = thread
				break
		return thread

	func is_all_thread_finished():
		for i in _threads.size():
			if _threads[i]:
				return false
		return true

	func is_all_task_finished():
		for i in _tasks.size():
			if _tasks[i]:
				return false
		return true
